pictures:
    type: rest
    prefix: /v1
    resource: Acme\ServerBundle\Controller\PictureController
    name_prefix: api_1_ # naming collision

users:
    type: rest
    prefix: /v1
    resource: Acme\ServerBundle\Controller\UserController
    name_prefix: api_1_ # naming collision

friends:
    type: rest
    prefix: /v1
    resource: Acme\ServerBundle\Controller\FriendController
    name_prefix: api_1_ # naming collision

comments:
    type: rest
    prefix: /v1
    resource: Acme\ServerBundle\Controller\PictureCommentController
    name_prefix: api_1_ # naming collision

likes:
    type: rest
    prefix: /v1
    resource: Acme\ServerBundle\Controller\PictureLikeController
    name_prefix: api_1_ # naming collision

tags:
    type: rest
    prefix: /v1
    resource: Acme\ServerBundle\Controller\PictureTagController
    name_prefix: api_1_ # naming collision

galleries:
    type: rest
    prefix: /v1
    resource: Acme\ServerBundle\Controller\GalleryController
    name_prefix: api_1_ # naming collision
