acme_server:
    type: rest
    prefix: /api
    resource: "@AcmeServerBundle/Resources/config/routes.yml"

app:
    resource: "@AppBundle/Controller/"
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc