acme_server:
    type: rest
    prefix: /api
    resource: "@AcmeServerBundle/Resources/config/routes.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc