security:
    providers:
        api_token_user_provider:
            id: api_token_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/api/v1
            stateless: true
            simple_preauth:
                authenticator: api_token_authenticator
            provider: api_token_user_provider
    access_control:
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/users, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: POST }