parameters:
    picture_entity: Acme\ServerBundle\Entity\Picture
    user_entity: Acme\ServerBundle\Entity\User
    friend_entity: Acme\ServerBundle\Entity\Friend
    picture_comment_entity: Acme\ServerBundle\Entity\PictureComment
    picture_like_entity: Acme\ServerBundle\Entity\PictureLike
    picture_tag_entity: Acme\ServerBundle\Entity\PictureTag
    tag_entity: Acme\ServerBundle\Entity\Tag
    gallery_entity: Acme\ServerBundle\Entity\PictureGallery
    ghp_entity: Acme\ServerBundle\Entity\GalleryHasPicture

services:
    api_token_user_provider:
        class: Acme\ServerBundle\Security\ApiTokenUserProvider
        arguments: ['@doctrine.orm.entity_manager']

    api_token_authenticator:
        class: Acme\ServerBundle\Security\ApiTokenAuthenticator
        arguments: ["@security.http_utils"]
        public: false

    rest.picture.helper:
        class: Acme\ServerBundle\Helper\PictureRestHelper
        arguments: ['@doctrine.orm.entity_manager', '@form.factory', '@image.thumbnail.helper', '%picture_entity%', '%images_upload_directory%']

    rest.auth.helper:
        class: Acme\ServerBundle\Helper\AuthHelper
        arguments: ['@doctrine.orm.entity_manager']

    rest.user.helper:
        class: Acme\ServerBundle\Helper\UserRestHelper
        arguments: ['@doctrine.orm.entity_manager', '@form.factory', '@rest.auth.helper', '%user_entity%']

    rest.friend.helper:
        class: Acme\ServerBundle\Helper\FriendRestHelper
        arguments: ['@doctrine.orm.entity_manager', '%friend_entity%']

    rest.comment.helper:
        class: Acme\ServerBundle\Helper\CommentRestHelper
        arguments: ['@doctrine.orm.entity_manager', '@form.factory', '%picture_comment_entity%']

    rest.like.helper:
        class: Acme\ServerBundle\Helper\LikeRestHelper
        arguments: ['@doctrine.orm.entity_manager', '@form.factory', '%picture_like_entity%']

    rest.tag.helper:
        class: Acme\ServerBundle\Helper\TagRestHelper
        arguments: ['@doctrine.orm.entity_manager', '@form.factory', '%tag_entity%']

    rest.gallery.helper:
        class: Acme\ServerBundle\Helper\GalleryRestHelper
        arguments: ['@doctrine.orm.entity_manager', '@form.factory', '%gallery_entity%', '%ghp_entity%']

    image.thumbnail.helper:
        class: Acme\ServerBundle\Helper\ImageThumbnailHelper
        arguments: ['%images_upload_directory%']