# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    picture_class: Acme\ServerBundle\Entity\Picture

services:
    rest.picture.helper:
        class: Acme\ServerBundle\Helper\PictureRestHelper
        arguments: ['@doctrine.orm.entity_manager', '@form.factory', '%picture_class%']

    rest.auth.helper:
        class: Acme\ServerBundle\Helper\AuthHelper
        arguments: ['@doctrine.orm.entity_manager']