<?php

namespace Acme\ServerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PictureGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureGalleryRepository extends EntityRepository
{
}
