<?php

namespace Acme\ServerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PictureTagRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureTagRepository extends EntityRepository
{
}
